# Generated by Django 5.0.4 on 2024-04-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0009_auto_20190815_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variacao',
            old_name='nome',
            new_name='name_variacao',
        ),
        migrations.RemoveField(
            model_name='variacao',
            name='nome_variacao',
        ),
    ]
