# Generated by Django 5.0.4 on 2024-04-26 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0010_rename_nome_variacao_name_variacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variacao',
            old_name='name_variacao',
            new_name='nome_variacao',
        ),
    ]
